### ISSUE TITLE
Unable to get gateway certificate through UI

### ISSUE THREAD

**Issue by jhwz** [chirpstack/chirpstack#35]
When clicking the 'Generate Certificate' button, get:
```
Error
Read gateway ca_cert
```
in the console:
```
{
    "code": 13,
    "message": "Read gateway ca_cert",
    "metadata": {
        "access-control-allow-credentials": "true",
        "access-control-allow-origin": "http://chirpstack.xxxx.com:8080",
        "access-control-expose-headers": "grpc-status,grpc-message",
        "alt-svc": "h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400",
        "cf-cache-status": "DYNAMIC",
        "cf-ray": "740fbf2ebeaba965-SYD",
        "connection": "keep-alive",
        "content-length": "0",
        "content-type": "application/grpc-web-text+proto",
        "date": "Fri, 26 Aug 2022 21:44:06 GMT",
        "grpc-message": "Read%20gateway%20ca_cert",
        "grpc-status": "13",
        "nel": "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}",
        "report-to": "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=taepJXzTrpDrX6Rt1ad2b32RgWGaDT4P1i4y30aluv%2FTCVcuXxOe4cCpZc1tMtgTI2emwv9eOsfguigiHDhdDEPK2qGmQHPHR4kF7rsnPYCLGlz5eYHUU%2Bw8CxrZrBOB2ij7W3f00IAiFiktRusqYA%3D%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}",
        "server": "cloudflare"
    }
}
```

**Comment by brocaar** [comment]
Have you configured this section of `chirpstack.toml`?

```toml
# Global gateway configuration.
# Please note that backend configuration can be found in the per-region
# configuration.
[gateway]

  # CA certificate and key file (optional).
  #
  # If setting the CA certificate and key file options, ChirpStack 
  # will generate client certificates which can be used by the gateway for
  # authentication and authorization. The Common Name of the certificate will
  # be set to the Gateway ID.
  ca_key=""
  ca_cert=""
```

See also: https://www.chirpstack.io/docs/guides/mosquitto-tls-configuration.html.
