### ISSUE TITLE
Extrem long load times at live LoRaWAN frames

### ISSUE THREAD

**Issue by lks-hrsch** [chirpstack/chirpstack#75]
We are currently facing extreme long load times for the live LoRaWAN frames. It seems related to #44, but there was no fix provided. 

Our current Setup:
* All up-to-date Kubernetes deployment of Chirpstack
* chirpstack/chirpstack:4.1
* chirpstack/chirpstack-gateway-bridge:4.0
* eclipse-mosquitto:2
* redis:7-alpine

Additional Info:
* on a Windows machine, we are receiving the live LoraWAN frames after 5 min++ 
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/45177922/211277214-51328421-2721-496e-a420-ea509142c214.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/45177922/211277290-08bb12a6-3ead-4881-b7ca-6cb40d3c6ce7.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/45177922/211277272-e1e3bcc9-ef38-422f-bbb1-70706ee00ec3.png)

* on a Mac machine, the response will never be received

The logs are looking correctly for me
```
[2m2023-01-09T08:47:00.899247Z[0m [34mDEBUG[0m [1mgRPC[0m[1m{[0m[3muri[0m[2m=[0m/api.InternalService/StreamGatewayFrames[1m}[0m[2m:[0m [2mchirpstack::api[0m[2m:[0m Started processing request
[2m2023-01-09T08:47:00.901267Z[0m [32m INFO[0m [1mgRPC[0m[1m{[0m[3muri[0m[2m=[0m/api.InternalService/StreamGatewayFrames[1m}[0m[2m:[0m [2mchirpstack::api[0m[2m:[0m Finished processing request [3mstatus[0m[2m=[0m"200" [3mlatency[0m[2m=[0m2.031913ms
[2m2023-01-09T08:47:00.901959Z[0m [35mTRACE[0m [2mchirpstack::framelog[0m[2m:[0m Frame-log received from stream [3mkey[0m[2m=[0mup [3mid[0m[2m=[0m1673253147620-0
[2m2023-01-09T08:47:00.902059Z[0m [35mTRACE[0m [2mchirpstack::framelog[0m[2m:[0m Frame-log received from stream [3mkey[0m[2m=[0mup [3mid[0m[2m=[0m1673253160243-0
[2m2023-01-09T08:47:00.902153Z[0m [35mTRACE[0m [2mchirpstack::api::internal[0m[2m:[0m Message received from Redis Stream channel
[2m2023-01-09T08:47:00.902162Z[0m [35mTRACE[0m [2mchirpstack::framelog[0m[2m:[0m Frame-log received from stream [3mkey[0m[2m=[0mup [3mid[0m[2m=[0m1673253169651-0
[2m2023-01-09T08:47:00.902170Z[0m [35mTRACE[0m [2mchirpstack::api::internal[0m[2m:[0m Message received from Redis Stream channel
[2m2023-01-09T08:47:00.902197Z[0m [35mTRACE[0m [2mchirpstack::framelog[0m[2m:[0m Frame-log received from stream [3mkey[0m[2m=[0mup [3mid[0m[2m=[0m1673253169751-0
[2m2023-01-09T08:47:00.902271Z[0m [35mTRACE[0m [2mchirpstack::api::internal[0m[2m:[0m Message received from Redis Stream channel
[2m2023-01-09T08:47:00.902279Z[0m [35mTRACE[0m [2mchirpstack::framelog[0m[2m:[0m Frame-log received from stream [3mkey[0m[2m=[0mup [3mid[0m[2m=[0m1673253469744-0
[2m2023-01-09T08:47:00.902298Z[0m [35mTRACE[0m [2mchirpstack::api::internal[0m[2m:[0m Message received from Redis Stream channel
[2m2023-01-09T08:47:00.902310Z[0m [35mTRACE[0m [2mchirpstack::framelog[0m[2m:[0m Frame-log received from stream [3mkey[0m[2m=[0mup [3mid[0m[2m=[0m1673253587700-0
[2m2023-01-09T08:47:00.902346Z[0m [35mTRACE[0m [2mchirpstack::api::internal[0m[2m:[0m Message received from Redis Stream channel
[2m2023-01-09T08:47:00.902361Z[0m [35mTRACE[0m [2mchirpstack::framelog[0m[2m:[0m Frame-log received from stream [3mkey[0m[2m=[0mup [3mid[0m[2m=[0m1673253747605-0
[2m2023-01-09T08:47:00.902369Z[0m [35mTRACE[0m [2mchirpstack::api::internal[0m[2m:[0m Message received from Redis Stream channel
[2m2023-01-09T08:47:00.902426Z[0m [35mTRACE[0m [2mchirpstack::framelog[0m[2m:[0m Frame-log received from stream [3mkey[0m[2m=[0mup [3mid[0m[2m=[0m1673253750509-0
[2m2023-01-09T08:47:00.902440Z[0m [35mTRACE[0m [2mchirpstack::api::internal[0m[2m:[0m Message received from Redis Stream channel
[2m2023-01-09T08:47:00.902461Z[0m [35mTRACE[0m [2mchirpstack::framelog[0m[2m:[0m Frame-log received from stream [3mkey[0m[2m=[0mup [3mid[0m[2m=[0m1673253769630-0
[2m2023-01-09T08:47:00.902467Z[0m [35mTRACE[0m [2mchirpstack::api::internal[0m[2m:[0m Message received from Redis Stream channel
[2m2023-01-09T08:47:00.902491Z[0m [35mTRACE[0m [2mchirpstack::api::internal[0m[2m:[0m Message received from Redis Stream channel
[2m2023-01-09T08:47:00.902495Z[0m [35mTRACE[0m [2mchirpstack::framelog[0m[2m:[0m Frame-log received from stream [3mkey[0m[2m=[0mup [3mid[0m[2m=[0m1673253769735-0
[2m2023-01-09T08:47:00.902557Z[0m [35mTRACE[0m [2mchirpstack::api::internal[0m[2m:[0m Message received from Redis Stream channel
```

If there is help or more information needed, please reach out to me.

**Comment by brocaar** [comment]
Are you using a proxy / NGINX ingress or something equal? In that case you must add some additional configuration to make sure that the gRPC calls on the `/api` prefix are correctly proxied. See for example this config example:

https://github.com/chirpstack/chirpstack-ansible-playbook/blob/master/roles/chirpstack/templates/chirpstack.nginx#L21

**Comment by lks-hrsch** [comment]
Yes, I am using the azure application-gateway I was looking there for the gRPC support and found this issue https://github.com/Azure/application-gateway-kubernetes-ingress/issues/1015. So, it seems not working because of the lack of gRPC support in the Ingress.


So as a fix I deployed a Traefik Ingress, and now it works perfectly.


It also works without configuring the `/api` prefix. I don't even understand why I need this they are pointing to the same resource, so why need I to differentiate between them?


My ingressRoute.yml
```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: chirpstack-ir-web
  namespace: cs-v4
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`xxx`)
    services:
    - kind: Service
      name: chirpstack
      namespace: cs-v4
      port: 8080

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: chirpstack-ir-websecure
  namespace: cs-v4
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`xxx`)
    services:
    - kind: Service
      name: chirpstack
      namespace: cs-v4
      port: 8080
  tls:                              
    secretName: chirpstack-tls-traefik

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chirpstack-tls-traefik
  namespace: cs-v4
spec:
  dnsNames:
    - xxx
  secretName: chirpstack-tls-traefik
  issuerRef:
    name: letsencrypt-traefik
    kind: ClusterIssuer
```
